### ISSUE TITLE
What is "User tag list" used for?

### ISSUE THREAD

**Issue by littlegolden** [Serakoi/flarumstaffbadge#4]
Is this is an unfinished feature?

**Comment by ThatKoffe** [comment]
> Is this is an unfinished feature?

Uhhh, could you screenshot what you mean? I havent worked on this in quiet a while.

**Comment by littlegolden** [comment]
When editing a use, there is a input to change User Tag List:

![image](https://github.com/user-attachments/assets/3ee50cad-9885-4fac-a0ef-1c18790444c2)

**Comment by ThatKoffe** [comment]
Aha, it's custom titles on a user profile
![image](https://github.com/user-attachments/assets/aa7d61c6-726c-4fa2-8c7f-19515b4b999d)
^ example

**Comment by ThatKoffe** [comment]
![image](https://github.com/user-attachments/assets/62bf1f22-7333-45be-980d-d7aea0b83df3)

@littlegolden true, it renders custom titles/badges on the user profile.

**Comment by littlegolden** [comment]
wow this is quick, thank you for the explain 😂. I was translating this title, and confused for, maybe it's better called "Extra badge list" or "Text badge list", what do you think?

**Comment by ThatKoffe** [comment]
Yeahhhh, not the perfect name for it huh. Uh, maybe like "Profile Titles" or something along those lines.
